#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Keitaro Takeda
# SPDX-License-Identifier: BSD-3-Clause

import sys
def check(onc):
    if onc.isalpha():
        if  97<= ord(onc) <=122:
            return 0  #アルファベット(a~z)なら０
        else:
            return 1  #アルファベット以外なら１
    elif onc.isdecimal():
        return 2      #数字なら２
    else:
        return 3       #どれでもないなら３

def alnum_tr(inp):
    if check(inp) == 0:
        outn = ord(inp)-96 #アルファベットは何番目かを返す
        return outn

    elif check(inp) == 1:
        outn = ord(inp)    #アルファベット以外はそのままコードを返す
        return outn

    elif check(inp) == 2:
       if 1 <= int(inp) <= 26: 
         return (chr(int(inp)+96)) #1~26番目と言われたらアルファベットを返す

       elif 27<= int(inp) <= 64:
           return '?' #コードがおそらく空の部分は？に 記号に対応したものも？に
       elif int(inp) == 0:
           return 0
       else:
           return chr(int(inp))#文字コードは文字に戻す
    elif check(inp)== 3:
        return '?' #それ以外はよく分からない

mode=0
out=[]
idl=[]

if len(sys.argv) > 1:
    inputs = sys.argv[1:]
else:
    # 標準入力をすべて読む（改行は無視）
    data = sys.stdin.read()
    inputs = data.split()

for n in inputs:
    if n == '!':
        mode = 1
    if n.isdecimal():
        out.append(alnum_tr(n))#数字を文字に変換してoutに加える

    elif isinstance(n,str): 
        for onc in n:
            idl.append(onc)#文字列なら1文字ずつに分ける

        for idx, inp in enumerate(idl):
            if mode == 0:
                idl[idx] = alnum_tr(inp)
            out.append(idl[idx])
        idl = []

if mode == 1:
    print(''.join(out))
else:
    print(*out)
